"""
Agent state model definitions.

Core dataclasses that represent the conversation and execution state of the agent.
These are persisted to Redis as JSON and deserialized on each turn.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal


@dataclass
class Message:
    """
    A single message in the conversation history.

    Attributes:
        role: "user" for user-submitted messages, "assistant" for LLM-generated responses,
              "tool" for tool execution results.
        content: The message text or tool output.
        created_at: ISO 8601 UTC timestamp when the message was created.
    """

    role: Literal["user", "assistant", "tool"]
    content: str
    created_at: datetime


@dataclass
class ToolCallRecord:
    """
    Record of a single tool invocation and its result.

    Attributes:
        tool_id: Fully-qualified tool identifier (e.g., "server.tool_name").
        status: "pending", "success", "failed", or "retried".
        output: Raw tool output (only populated on success).
        error: Error message (only populated on failure).
        attempt_count: Number of execution attempts (including retries).
        duration_ms: Total execution time in milliseconds.
        fallback_used: True if a fallback tool was invoked due to primary tool failure.
    """

    tool_id: str
    status: Literal["pending", "success", "failed", "retried"]
    output: Any | None = None
    error: str | None = None
    attempt_count: int = 1
    duration_ms: int = 0
    fallback_used: bool = False


@dataclass
class AgentState:
    """
    Primary unit of session state, persisted to Redis.

    Represents the complete conversation context and execution state for a single
    client session. Serialized to JSON and stored at Redis key `session:{session_id}`.

    Attributes:
        session_id: UUID4 string; created on first turn and never changes.
        created_at: ISO 8601 UTC; timestamp of session creation.
        last_activity: ISO 8601 UTC; updated on every turn.

        messages: Ordered, append-only list of all messages in the conversation.
                 Last 5 messages used as context window for LLM.
        turn_count: Number of turns executed so far. Incremented before graph execution.
                   Requests rejected when turn_count >= settings.max_turns.

        current_input: Validated user message (1–4096 chars) for this turn.
        current_thought: LLM chain-of-thought reasoning generated by node_think.
        current_decision: "use_tool" | "direct_response" | "error" determined by node_decide_action.

        selected_tool_id: Fully-qualified tool ID if current_decision is "use_tool", else None.
        tool_calls_this_turn: List of ToolCallRecord for tools invoked this turn.
        current_tool_output: Raw tool output from node_tool_result.

        last_error: Error message from last failed turn.
        error_count: Cumulative error count across all turns.

        available_tools: Snapshot of ToolDefinition.__dict__ at startup.
                        Presented to LLM for selection.
        metadata: Client-provided metadata from ChatRequest (e.g., user_id, session_name).
    """

    # Identity
    session_id: str
    """UUID4 string; created on first turn."""

    created_at: datetime
    """ISO 8601 UTC; timestamp of session creation."""

    last_activity: datetime
    """ISO 8601 UTC; updated on every turn for TTL tracking."""

    # Conversation
    messages: list[Message] = field(default_factory=list)
    """Ordered, append-only conversation history."""

    turn_count: int = 0
    """Number of turns executed. Incremented before graph execution."""

    # Current execution (reset each turn)
    current_input: str = ""
    """Validated user message for this turn (1–4096 chars)."""

    current_thought: str | None = None
    """LLM chain-of-thought from node_think."""

    current_decision: str | None = None
    """'use_tool' | 'direct_response' | 'error' from node_decide_action."""

    # Tool execution (reset each turn)
    selected_tool_id: str | None = None
    """Fully-qualified tool ID if current_decision is 'use_tool'."""

    tool_calls_this_turn: list[ToolCallRecord] = field(default_factory=list)
    """ToolCallRecord for each tool invoked in this turn."""

    current_tool_output: Any | None = None
    """Raw tool output from node_tool_result."""

    # Error state (reset each turn)
    last_error: str | None = None
    """Error message from the last failed turn."""

    error_count: int = 0
    """Cumulative error count across all turns."""

    # Startup-loaded, not persisted per-turn
    available_tools: list[dict] = field(default_factory=list)
    """Snapshot of ToolDefinition.__dict__ at startup for LLM selection."""

    metadata: dict = field(default_factory=dict)
    """Client metadata from ChatRequest (user_id, session_name, etc.)."""
